M48
; DRILL file {KiCad (6.0.7)} date Fri Aug  5 13:27:33 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-05T13:27:33+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X3.3661Y-1.1417
X3.3661Y-3.6614
X4.8819Y-1.1417
X4.8819Y-3.6614
T0
M30
