M48
; DRILL file {KiCad (6.0.2)} date Mon Nov  7 20:39:00 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-11-07T20:39:00+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.1814Y-3.6791
X4.5279Y-3.6791
X4.7814Y-3.6791
X5.1279Y-3.6791
T2
X1.64Y-0.99
X1.65Y-4.5
X5.15Y-1.0
X5.15Y-4.5
T0
M30
